In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data\stud.csv')

In [3]:
df.head(3)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [4]:
x = df.drop('math_score',axis = 1)
y = df['math_score']

In [5]:
categorical_columns = x.select_dtypes(include='object').columns
numerical_columns = x.select_dtypes(exclude='object').columns

In [6]:
for feature in df.columns:
  if df[feature].dtype == 'O':
    print(f"Unique features in {feature} : {df[feature].unique()}")

Unique features in gender : ['female' 'male']
Unique features in race_ethnicity : ['group B' 'group C' 'group A' 'group D' 'group E']
Unique features in parental_level_of_education : ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Unique features in lunch : ['standard' 'free/reduced']
Unique features in test_preparation_course : ['none' 'completed']

In [7]:
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
  [("StandardScaler",numerical_transformer,numerical_columns),
   ("OneHotEncoder",categorical_transformer,categorical_columns)]
)

In [8]:
x = preprocessor.fit_transform(x)

In [9]:
x.shape

(1000, 19)

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [11]:
models = {
  "Linear Regression":LinearRegression(),
  "AdaBoost Regressor":AdaBoostRegressor(),
  "DecisionTree Regressor":DecisionTreeRegressor(),
  "CatBoost Regressor":CatBoostRegressor(),
  "RandomForest Regressor":RandomForestRegressor(),
  "KNeighbors Regressor":KNeighborsRegressor(),
  "SVR":SVR(),
  "XGB Regressor":XGBRegressor(),
  "Ridge":Ridge(),
  "Lasso":Lasso()
}

In [12]:
def scores(true,prediction):
  mse = mean_squared_error(true,prediction)
  mae = mean_absolute_error(true,prediction)
  r2 = r2_score(true,prediction)
  rmse = np.sqrt(mse)

  return mse,mae,r2,rmse

In [13]:
model_list = []
r2_list = []
for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(x_train,y_train)

  y_train_pred = model.predict(x_train)
  y_test_pred = model.predict(x_test)

  train_mse,train_mae,train_r2,train_rmse = scores(y_train,y_train_pred)
  test_mse,test_mae,test_r2,test_rmse = scores(y_test,y_test_pred)

  model_list.append(list(models.keys())[i])
  r2_list.append(test_r2)

  print(list(models.keys())[i])
  print("-"*50)
  print("Training model prediction scores")
  print()
  print(f"Training model mean squared error score : {train_mse}")
  print(f"Training model root mean squared error score : {train_rmse}")
  print(f"Training model mean absolute error score : {train_mae}")
  print(f"Training model mean absolute error score : {train_r2}")
  print("-"*50)
  print("Test model prediction scores")
  print()
  print(f"Test model mean squared error score : {test_mse}")
  print(f"Test model root mean squared error score : {test_rmse}")
  print(f"Test model mean absolute error score : {test_mae}")
  print(f"Test model mean absolute error score : {test_r2}")
  print("="*50)

Linear Regression
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 28.33487038064859
Training model root mean squared error score : 5.323050852720514
Training model mean absolute error score : 4.266711846071956
Training model mean absolute error score : 0.8743172040139593
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 29.095169866715466
Test model root mean squared error score : 5.3939938697328405
Test model mean absolute error score : 4.214763142474849
Test model mean absolute error score : 0.8804332983749565
==================================================
AdaBoost Regressor
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 33.98307678759046
Training model root mean squared error score : 5.829500560733352
Training model mean absolute error score : 4.76961539788581
Training model mean absolute error score : 0.8492638911173688
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 35.5883632314465
Test model root mean squared error score : 5.965598312947872
Test model mean absolute error score : 4.643444035118866
Test model mean absolute error score : 0.8537494976894461
==================================================
DecisionTree Regressor
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 0.078125
Training model root mean squared error score : 0.2795084971874737
Training model mean absolute error score : 0.01875
Training model mean absolute error score : 0.9996534669718089
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 64.875
Test model root mean squared error score : 8.054501846793507
Test model mean absolute error score : 6.285
Test model mean absolute error score : 0.7333959621662672
==================================================
Learning rate set to 0.039525
0:	learn: 14.5987177	total: 172ms	remaining: 2m 51s
1:	learn: 14.2251886	total: 175ms	remaining: 1m 27s
2:	learn: 13.8866124	total: 182ms	remaining: 1m
3:	learn: 13.5235688	total: 193ms	remaining: 48.1s
4:	learn: 13.1887021	total: 197ms	remaining: 39.1s
5:	learn: 12.9124226	total: 199ms	remaining: 33s
6:	learn: 12.6000335	total: 203ms	remaining: 28.7s
7:	learn: 12.3299057	total: 207ms	remaining: 25.7s
8:	learn: 12.0660619	total: 210ms	remaining: 23.1s
9:	learn: 11.7730981	total: 213ms	remaining: 21.1s
10:	learn: 11.4922764	total: 216ms	remaining: 19.5s
11:	learn: 11.2626483	total: 219ms	remaining: 18.1s
12:	learn: 11.0426039	total: 222ms	remaining: 16.9s
13:	learn: 10.7991693	total: 225ms	remaining: 15.9s
14:	learn: 10.5541002	total: 228ms	remaining: 15s
15:	learn: 10.3191811	total: 231ms	remaining: 14.2s
16:	learn: 10.1000444	total: 234ms	remaining: 13.5s
17:	learn: 9.8945567	total: 237ms	remaining: 12.9s
18:	learn: 9.6901741	total: 241ms	remaining: 12.4s
19:	learn: 9.5060349	total: 244ms	remaining: 11.9s
20:	learn: 9.3385246	total: 247ms	remaining: 11.5s
21:	learn: 9.1702033	total: 250ms	remaining: 11.1s
22:	learn: 9.0103000	total: 253ms	remaining: 10.8s
23:	learn: 8.8438667	total: 256ms	remaining: 10.4s
24:	learn: 8.6905481	total: 259ms	remaining: 10.1s
25:	learn: 8.5553077	total: 262ms	remaining: 9.8s
26:	learn: 8.4138513	total: 264ms	remaining: 9.53s
27:	learn: 8.2925602	total: 266ms	remaining: 9.24s
28:	learn: 8.1621938	total: 268ms	remaining: 8.98s
29:	learn: 8.0407363	total: 270ms	remaining: 8.72s
30:	learn: 7.9212203	total: 271ms	remaining: 8.47s
31:	learn: 7.8095890	total: 273ms	remaining: 8.25s
32:	learn: 7.6996758	total: 274ms	remaining: 8.03s
33:	learn: 7.6064527	total: 276ms	remaining: 7.84s
34:	learn: 7.4988803	total: 277ms	remaining: 7.64s
35:	learn: 7.4011587	total: 278ms	remaining: 7.45s
36:	learn: 7.3064311	total: 279ms	remaining: 7.27s
37:	learn: 7.2238635	total: 281ms	remaining: 7.1s
38:	learn: 7.1434777	total: 282ms	remaining: 6.94s
39:	learn: 7.0628171	total: 283ms	remaining: 6.79s
40:	learn: 6.9907934	total: 284ms	remaining: 6.63s
41:	learn: 6.9318622	total: 285ms	remaining: 6.49s
42:	learn: 6.8582966	total: 286ms	remaining: 6.36s
43:	learn: 6.7862682	total: 287ms	remaining: 6.23s
44:	learn: 6.7171185	total: 288ms	remaining: 6.11s
45:	learn: 6.6529481	total: 289ms	remaining: 5.99s
46:	learn: 6.5896861	total: 290ms	remaining: 5.87s
47:	learn: 6.5312831	total: 290ms	remaining: 5.76s
48:	learn: 6.4713680	total: 291ms	remaining: 5.65s
49:	learn: 6.4164814	total: 292ms	remaining: 5.55s
50:	learn: 6.3698708	total: 293ms	remaining: 5.45s
51:	learn: 6.3256781	total: 294ms	remaining: 5.36s
52:	learn: 6.2757661	total: 295ms	remaining: 5.26s
53:	learn: 6.2247740	total: 295ms	remaining: 5.18s
54:	learn: 6.1822493	total: 296ms	remaining: 5.09s
55:	learn: 6.1399042	total: 297ms	remaining: 5.01s
56:	learn: 6.1005255	total: 298ms	remaining: 4.93s
57:	learn: 6.0625686	total: 299ms	remaining: 4.85s
58:	learn: 6.0305593	total: 299ms	remaining: 4.77s
59:	learn: 5.9979314	total: 300ms	remaining: 4.7s
60:	learn: 5.9641038	total: 301ms	remaining: 4.63s
61:	learn: 5.9337297	total: 301ms	remaining: 4.56s
62:	learn: 5.9019327	total: 302ms	remaining: 4.49s
63:	learn: 5.8737278	total: 303ms	remaining: 4.43s
64:	learn: 5.8464857	total: 304ms	remaining: 4.37s
65:	learn: 5.8206309	total: 304ms	remaining: 4.31s
66:	learn: 5.7936462	total: 305ms	remaining: 4.25s
67:	learn: 5.7653886	total: 306ms	remaining: 4.19s
68:	learn: 5.7470739	total: 306ms	remaining: 4.13s
69:	learn: 5.7223152	total: 307ms	remaining: 4.08s
70:	learn: 5.6999706	total: 308ms	remaining: 4.03s
71:	learn: 5.6827326	total: 308ms	remaining: 3.97s
72:	learn: 5.6635258	total: 309ms	remaining: 3.93s
73:	learn: 5.6423816	total: 310ms	remaining: 3.88s
74:	learn: 5.6214048	total: 311ms	remaining: 3.83s
75:	learn: 5.6024601	total: 311ms	remaining: 3.78s
76:	learn: 5.5873376	total: 312ms	remaining: 3.74s
77:	learn: 5.5723930	total: 312ms	remaining: 3.69s
78:	learn: 5.5584258	total: 313ms	remaining: 3.65s
79:	learn: 5.5415189	total: 314ms	remaining: 3.61s
80:	learn: 5.5261573	total: 314ms	remaining: 3.57s
81:	learn: 5.5117470	total: 315ms	remaining: 3.53s
82:	learn: 5.5049750	total: 316ms	remaining: 3.48s
83:	learn: 5.4939805	total: 316ms	remaining: 3.45s
84:	learn: 5.4807455	total: 317ms	remaining: 3.41s
85:	learn: 5.4640520	total: 318ms	remaining: 3.37s
86:	learn: 5.4491437	total: 318ms	remaining: 3.34s
87:	learn: 5.4382554	total: 319ms	remaining: 3.3s
88:	learn: 5.4259279	total: 319ms	remaining: 3.27s
89:	learn: 5.4123312	total: 320ms	remaining: 3.24s
90:	learn: 5.4006915	total: 321ms	remaining: 3.21s
91:	learn: 5.3916187	total: 322ms	remaining: 3.17s
92:	learn: 5.3807666	total: 323ms	remaining: 3.15s
93:	learn: 5.3722072	total: 323ms	remaining: 3.11s
94:	learn: 5.3629188	total: 324ms	remaining: 3.08s
95:	learn: 5.3482923	total: 324ms	remaining: 3.06s
96:	learn: 5.3397723	total: 325ms	remaining: 3.03s
97:	learn: 5.3315160	total: 326ms	remaining: 3s
98:	learn: 5.3238616	total: 327ms	remaining: 2.97s
99:	learn: 5.3132773	total: 327ms	remaining: 2.94s
100:	learn: 5.3068563	total: 328ms	remaining: 2.92s
101:	learn: 5.2965206	total: 329ms	remaining: 2.9s
102:	learn: 5.2883508	total: 330ms	remaining: 2.88s
103:	learn: 5.2799335	total: 331ms	remaining: 2.85s
104:	learn: 5.2717891	total: 332ms	remaining: 2.83s
105:	learn: 5.2626847	total: 332ms	remaining: 2.8s
106:	learn: 5.2516198	total: 333ms	remaining: 2.78s
107:	learn: 5.2410122	total: 334ms	remaining: 2.75s
108:	learn: 5.2326840	total: 334ms	remaining: 2.73s
109:	learn: 5.2242671	total: 335ms	remaining: 2.71s
110:	learn: 5.2163250	total: 336ms	remaining: 2.69s
111:	learn: 5.2111025	total: 336ms	remaining: 2.67s
112:	learn: 5.2063643	total: 337ms	remaining: 2.65s
113:	learn: 5.1969376	total: 338ms	remaining: 2.62s
114:	learn: 5.1907460	total: 338ms	remaining: 2.6s
115:	learn: 5.1818852	total: 339ms	remaining: 2.58s
116:	learn: 5.1782936	total: 339ms	remaining: 2.56s
117:	learn: 5.1709914	total: 340ms	remaining: 2.54s
118:	learn: 5.1662572	total: 341ms	remaining: 2.52s
119:	learn: 5.1614212	total: 342ms	remaining: 2.5s
120:	learn: 5.1582235	total: 342ms	remaining: 2.49s
121:	learn: 5.1547099	total: 343ms	remaining: 2.47s
122:	learn: 5.1463881	total: 344ms	remaining: 2.45s
123:	learn: 5.1395294	total: 345ms	remaining: 2.44s
124:	learn: 5.1342760	total: 346ms	remaining: 2.42s
125:	learn: 5.1285361	total: 346ms	remaining: 2.4s
126:	learn: 5.1233004	total: 347ms	remaining: 2.38s
127:	learn: 5.1162005	total: 348ms	remaining: 2.37s
128:	learn: 5.1087287	total: 348ms	remaining: 2.35s
129:	learn: 5.1040759	total: 349ms	remaining: 2.33s
130:	learn: 5.1003176	total: 350ms	remaining: 2.32s
131:	learn: 5.0958142	total: 351ms	remaining: 2.31s
132:	learn: 5.0921469	total: 351ms	remaining: 2.29s
133:	learn: 5.0852583	total: 352ms	remaining: 2.27s
134:	learn: 5.0792194	total: 353ms	remaining: 2.26s
135:	learn: 5.0764768	total: 354ms	remaining: 2.25s
136:	learn: 5.0721339	total: 354ms	remaining: 2.23s
137:	learn: 5.0670316	total: 355ms	remaining: 2.22s
138:	learn: 5.0613583	total: 358ms	remaining: 2.22s
139:	learn: 5.0567591	total: 359ms	remaining: 2.21s
140:	learn: 5.0502540	total: 360ms	remaining: 2.19s
141:	learn: 5.0483765	total: 361ms	remaining: 2.18s
142:	learn: 5.0426038	total: 361ms	remaining: 2.17s
143:	learn: 5.0374773	total: 362ms	remaining: 2.15s
144:	learn: 5.0323049	total: 363ms	remaining: 2.14s
145:	learn: 5.0259762	total: 364ms	remaining: 2.13s
146:	learn: 5.0195245	total: 364ms	remaining: 2.11s
147:	learn: 5.0175694	total: 365ms	remaining: 2.1s
148:	learn: 5.0089624	total: 366ms	remaining: 2.09s
149:	learn: 5.0038803	total: 366ms	remaining: 2.08s
150:	learn: 4.9963876	total: 367ms	remaining: 2.06s
151:	learn: 4.9933617	total: 368ms	remaining: 2.05s
152:	learn: 4.9900575	total: 368ms	remaining: 2.04s
153:	learn: 4.9869088	total: 369ms	remaining: 2.03s
154:	learn: 4.9852072	total: 374ms	remaining: 2.04s
155:	learn: 4.9790035	total: 375ms	remaining: 2.03s
156:	learn: 4.9731422	total: 376ms	remaining: 2.02s
157:	learn: 4.9670567	total: 376ms	remaining: 2.01s
158:	learn: 4.9614607	total: 377ms	remaining: 1.99s
159:	learn: 4.9542404	total: 378ms	remaining: 1.98s
160:	learn: 4.9523207	total: 378ms	remaining: 1.97s
161:	learn: 4.9483378	total: 379ms	remaining: 1.96s
162:	learn: 4.9432286	total: 380ms	remaining: 1.95s
163:	learn: 4.9385458	total: 381ms	remaining: 1.94s
164:	learn: 4.9353306	total: 381ms	remaining: 1.93s
165:	learn: 4.9320515	total: 382ms	remaining: 1.92s
166:	learn: 4.9289642	total: 382ms	remaining: 1.91s
167:	learn: 4.9228602	total: 383ms	remaining: 1.9s
168:	learn: 4.9176688	total: 384ms	remaining: 1.89s
169:	learn: 4.9103654	total: 385ms	remaining: 1.88s
170:	learn: 4.9064572	total: 385ms	remaining: 1.87s
171:	learn: 4.9019965	total: 386ms	remaining: 1.86s
172:	learn: 4.8968162	total: 387ms	remaining: 1.85s
173:	learn: 4.8911231	total: 387ms	remaining: 1.84s
174:	learn: 4.8876302	total: 388ms	remaining: 1.83s
175:	learn: 4.8852597	total: 389ms	remaining: 1.82s
176:	learn: 4.8806597	total: 390ms	remaining: 1.81s
177:	learn: 4.8772997	total: 390ms	remaining: 1.8s
178:	learn: 4.8740388	total: 391ms	remaining: 1.79s
179:	learn: 4.8694370	total: 392ms	remaining: 1.78s
180:	learn: 4.8612687	total: 392ms	remaining: 1.77s
181:	learn: 4.8586731	total: 393ms	remaining: 1.77s
182:	learn: 4.8540362	total: 394ms	remaining: 1.76s
183:	learn: 4.8513024	total: 395ms	remaining: 1.75s
184:	learn: 4.8475101	total: 395ms	remaining: 1.74s
185:	learn: 4.8456917	total: 396ms	remaining: 1.73s
186:	learn: 4.8420586	total: 396ms	remaining: 1.72s
187:	learn: 4.8386237	total: 397ms	remaining: 1.72s
188:	learn: 4.8346022	total: 398ms	remaining: 1.71s
189:	learn: 4.8308590	total: 399ms	remaining: 1.7s
190:	learn: 4.8275905	total: 399ms	remaining: 1.69s
191:	learn: 4.8222462	total: 400ms	remaining: 1.68s
192:	learn: 4.8166864	total: 401ms	remaining: 1.68s
193:	learn: 4.8147971	total: 402ms	remaining: 1.67s
194:	learn: 4.8116394	total: 402ms	remaining: 1.66s
195:	learn: 4.8048134	total: 403ms	remaining: 1.65s
196:	learn: 4.8025161	total: 404ms	remaining: 1.65s
197:	learn: 4.8000879	total: 404ms	remaining: 1.64s
198:	learn: 4.7947731	total: 405ms	remaining: 1.63s
199:	learn: 4.7916648	total: 406ms	remaining: 1.62s
200:	learn: 4.7859899	total: 407ms	remaining: 1.62s
201:	learn: 4.7823871	total: 408ms	remaining: 1.61s
202:	learn: 4.7786237	total: 408ms	remaining: 1.6s
203:	learn: 4.7757722	total: 409ms	remaining: 1.6s
204:	learn: 4.7702310	total: 410ms	remaining: 1.59s
205:	learn: 4.7644967	total: 411ms	remaining: 1.58s
206:	learn: 4.7631387	total: 411ms	remaining: 1.57s
207:	learn: 4.7580533	total: 412ms	remaining: 1.57s
208:	learn: 4.7550638	total: 413ms	remaining: 1.56s
209:	learn: 4.7524653	total: 413ms	remaining: 1.55s
210:	learn: 4.7480674	total: 414ms	remaining: 1.55s
211:	learn: 4.7441633	total: 415ms	remaining: 1.54s
212:	learn: 4.7366709	total: 416ms	remaining: 1.53s
213:	learn: 4.7334926	total: 416ms	remaining: 1.53s
214:	learn: 4.7318646	total: 417ms	remaining: 1.52s
215:	learn: 4.7283983	total: 418ms	remaining: 1.51s
216:	learn: 4.7238660	total: 418ms	remaining: 1.51s
217:	learn: 4.7234834	total: 419ms	remaining: 1.5s
218:	learn: 4.7209542	total: 420ms	remaining: 1.5s
219:	learn: 4.7161734	total: 420ms	remaining: 1.49s
220:	learn: 4.7105640	total: 421ms	remaining: 1.48s
221:	learn: 4.7071603	total: 422ms	remaining: 1.48s
222:	learn: 4.7040835	total: 422ms	remaining: 1.47s
223:	learn: 4.7025018	total: 423ms	remaining: 1.47s
224:	learn: 4.7002697	total: 424ms	remaining: 1.46s
225:	learn: 4.6953463	total: 424ms	remaining: 1.45s
226:	learn: 4.6897693	total: 425ms	remaining: 1.45s
227:	learn: 4.6879195	total: 426ms	remaining: 1.44s
228:	learn: 4.6829821	total: 426ms	remaining: 1.44s
229:	learn: 4.6795787	total: 427ms	remaining: 1.43s
230:	learn: 4.6757514	total: 428ms	remaining: 1.42s
231:	learn: 4.6727107	total: 429ms	remaining: 1.42s
232:	learn: 4.6690533	total: 429ms	remaining: 1.41s
233:	learn: 4.6675957	total: 430ms	remaining: 1.41s
234:	learn: 4.6642413	total: 431ms	remaining: 1.4s
235:	learn: 4.6622470	total: 431ms	remaining: 1.4s
236:	learn: 4.6586684	total: 432ms	remaining: 1.39s
237:	learn: 4.6580176	total: 433ms	remaining: 1.39s
238:	learn: 4.6576567	total: 433ms	remaining: 1.38s
239:	learn: 4.6532429	total: 434ms	remaining: 1.37s
240:	learn: 4.6507302	total: 435ms	remaining: 1.37s
241:	learn: 4.6476713	total: 436ms	remaining: 1.36s
242:	learn: 4.6455060	total: 436ms	remaining: 1.36s
243:	learn: 4.6412979	total: 437ms	remaining: 1.35s
244:	learn: 4.6379811	total: 438ms	remaining: 1.35s
245:	learn: 4.6350623	total: 438ms	remaining: 1.34s
246:	learn: 4.6316060	total: 439ms	remaining: 1.34s
247:	learn: 4.6302155	total: 440ms	remaining: 1.33s
248:	learn: 4.6272981	total: 441ms	remaining: 1.33s
249:	learn: 4.6246918	total: 441ms	remaining: 1.32s
250:	learn: 4.6218401	total: 442ms	remaining: 1.32s
251:	learn: 4.6196021	total: 443ms	remaining: 1.31s
252:	learn: 4.6135840	total: 443ms	remaining: 1.31s
253:	learn: 4.6119388	total: 444ms	remaining: 1.3s
254:	learn: 4.6087070	total: 445ms	remaining: 1.3s
255:	learn: 4.6047716	total: 445ms	remaining: 1.29s
256:	learn: 4.6042313	total: 446ms	remaining: 1.29s
257:	learn: 4.6007504	total: 447ms	remaining: 1.28s
258:	learn: 4.5964883	total: 447ms	remaining: 1.28s
259:	learn: 4.5947078	total: 448ms	remaining: 1.27s
260:	learn: 4.5888180	total: 449ms	remaining: 1.27s
261:	learn: 4.5850542	total: 449ms	remaining: 1.26s
262:	learn: 4.5814714	total: 450ms	remaining: 1.26s
263:	learn: 4.5775552	total: 451ms	remaining: 1.26s
264:	learn: 4.5745714	total: 452ms	remaining: 1.25s
265:	learn: 4.5730292	total: 453ms	remaining: 1.25s
266:	learn: 4.5713262	total: 454ms	remaining: 1.25s
267:	learn: 4.5710192	total: 455ms	remaining: 1.24s
268:	learn: 4.5657666	total: 455ms	remaining: 1.24s
269:	learn: 4.5633835	total: 456ms	remaining: 1.23s
270:	learn: 4.5581658	total: 457ms	remaining: 1.23s
271:	learn: 4.5562921	total: 457ms	remaining: 1.22s
272:	learn: 4.5493838	total: 458ms	remaining: 1.22s
273:	learn: 4.5462275	total: 459ms	remaining: 1.22s
274:	learn: 4.5406210	total: 460ms	remaining: 1.21s
275:	learn: 4.5328982	total: 461ms	remaining: 1.21s
276:	learn: 4.5297574	total: 461ms	remaining: 1.2s
277:	learn: 4.5257929	total: 462ms	remaining: 1.2s
278:	learn: 4.5215722	total: 463ms	remaining: 1.2s
279:	learn: 4.5188181	total: 464ms	remaining: 1.19s
280:	learn: 4.5140123	total: 464ms	remaining: 1.19s
281:	learn: 4.5083314	total: 465ms	remaining: 1.18s
282:	learn: 4.5060385	total: 466ms	remaining: 1.18s
283:	learn: 4.5058056	total: 466ms	remaining: 1.18s
284:	learn: 4.5015504	total: 467ms	remaining: 1.17s
285:	learn: 4.4946926	total: 468ms	remaining: 1.17s
286:	learn: 4.4893302	total: 469ms	remaining: 1.16s
287:	learn: 4.4848270	total: 469ms	remaining: 1.16s
288:	learn: 4.4782854	total: 470ms	remaining: 1.16s
289:	learn: 4.4753117	total: 471ms	remaining: 1.15s
290:	learn: 4.4715813	total: 471ms	remaining: 1.15s
291:	learn: 4.4691650	total: 472ms	remaining: 1.14s
292:	learn: 4.4620680	total: 473ms	remaining: 1.14s
293:	learn: 4.4585410	total: 474ms	remaining: 1.14s
294:	learn: 4.4557575	total: 474ms	remaining: 1.13s
295:	learn: 4.4530274	total: 476ms	remaining: 1.13s
296:	learn: 4.4506593	total: 477ms	remaining: 1.13s
297:	learn: 4.4446969	total: 477ms	remaining: 1.12s
298:	learn: 4.4420528	total: 479ms	remaining: 1.12s
299:	learn: 4.4400368	total: 479ms	remaining: 1.12s
300:	learn: 4.4350171	total: 480ms	remaining: 1.11s
301:	learn: 4.4299621	total: 481ms	remaining: 1.11s
302:	learn: 4.4276663	total: 482ms	remaining: 1.11s
303:	learn: 4.4250300	total: 482ms	remaining: 1.1s
304:	learn: 4.4225888	total: 483ms	remaining: 1.1s
305:	learn: 4.4189367	total: 484ms	remaining: 1.1s
306:	learn: 4.4168880	total: 484ms	remaining: 1.09s
307:	learn: 4.4137734	total: 485ms	remaining: 1.09s
308:	learn: 4.4111294	total: 486ms	remaining: 1.09s
309:	learn: 4.4085082	total: 487ms	remaining: 1.08s
310:	learn: 4.4048803	total: 487ms	remaining: 1.08s
311:	learn: 4.4045938	total: 488ms	remaining: 1.07s
312:	learn: 4.4021399	total: 489ms	remaining: 1.07s
313:	learn: 4.4002847	total: 489ms	remaining: 1.07s
314:	learn: 4.3958055	total: 490ms	remaining: 1.06s
315:	learn: 4.3928388	total: 491ms	remaining: 1.06s
316:	learn: 4.3892131	total: 491ms	remaining: 1.06s
317:	learn: 4.3861981	total: 492ms	remaining: 1.05s
318:	learn: 4.3850542	total: 493ms	remaining: 1.05s
319:	learn: 4.3793646	total: 493ms	remaining: 1.05s
320:	learn: 4.3783876	total: 494ms	remaining: 1.04s
321:	learn: 4.3758167	total: 495ms	remaining: 1.04s
322:	learn: 4.3746002	total: 495ms	remaining: 1.04s
323:	learn: 4.3709890	total: 496ms	remaining: 1.03s
324:	learn: 4.3674185	total: 497ms	remaining: 1.03s
325:	learn: 4.3635846	total: 498ms	remaining: 1.03s
326:	learn: 4.3607707	total: 498ms	remaining: 1.02s
327:	learn: 4.3586758	total: 499ms	remaining: 1.02s
328:	learn: 4.3542282	total: 500ms	remaining: 1.02s
329:	learn: 4.3537734	total: 500ms	remaining: 1.02s
330:	learn: 4.3516480	total: 501ms	remaining: 1.01s
331:	learn: 4.3482099	total: 503ms	remaining: 1.01s
332:	learn: 4.3458527	total: 504ms	remaining: 1.01s
333:	learn: 4.3423734	total: 504ms	remaining: 1s
334:	learn: 4.3408144	total: 505ms	remaining: 1s
335:	learn: 4.3397071	total: 506ms	remaining: 999ms
336:	learn: 4.3354308	total: 506ms	remaining: 996ms
337:	learn: 4.3352189	total: 507ms	remaining: 993ms
338:	learn: 4.3285072	total: 508ms	remaining: 990ms
339:	learn: 4.3261407	total: 508ms	remaining: 987ms
340:	learn: 4.3237856	total: 509ms	remaining: 984ms
341:	learn: 4.3206325	total: 510ms	remaining: 981ms
342:	learn: 4.3197372	total: 511ms	remaining: 978ms
343:	learn: 4.3180009	total: 511ms	remaining: 975ms
344:	learn: 4.3127136	total: 512ms	remaining: 972ms
345:	learn: 4.3082208	total: 513ms	remaining: 969ms

  File "c:\ML_Project\venv\lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
  File "c:\ML_Project\venv\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\ML_Project\venv\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\ML_Project\venv\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

KNeighbors Regressor
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 32.635549999999995
Training model root mean squared error score : 5.712753276660913
Training model mean absolute error score : 4.51675
Training model mean absolute error score : 0.8552410116072555
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 52.617
Test model root mean squared error score : 7.253757646902741
Test model mean absolute error score : 5.619
Test model mean absolute error score : 0.7837702557426202
==================================================
SVR
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 43.257024268031365
Training model root mean squared error score : 6.57700724251018
Training model mean absolute error score : 4.869189452384867
Training model mean absolute error score : 0.8081281585902299
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 66.04200493745648
Test model root mean squared error score : 8.126623218622633
Test model mean absolute error score : 5.401539244496997
Test model mean absolute error score : 0.7286001513223705
==================================================
XGB Regressor
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 1.0146163961652577
Training model root mean squared error score : 1.0072816866027385
Training model mean absolute error score : 0.6874666035175323
Training model mean absolute error score : 0.9954995444196413
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 43.50391987982302
Test model root mean squared error score : 6.595750137764697
Test model mean absolute error score : 5.103629446029663
Test model mean absolute error score : 0.8212204901494256
==================================================
Ridge
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 28.33778823308244
Training model root mean squared error score : 5.323324922741654
Training model mean absolute error score : 4.264987823725981
Training model mean absolute error score : 0.8743042615212909
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 29.056272192348306
Test model root mean squared error score : 5.39038701693564
Test model mean absolute error score : 4.211100688014261
Test model mean absolute error score : 0.8805931485028737
==================================================
Lasso
--------------------------------------------------
Training model prediction scores

Training model mean squared error score : 43.47829788272618
Training model root mean squared error score : 6.593807540619166
Training model mean absolute error score : 5.206296077972952
Training model mean absolute error score : 0.8071466723085148
--------------------------------------------------
Test model prediction scores

Test model mean squared error score : 42.50633235127344
Test model root mean squared error score : 6.519688056285626
Test model mean absolute error score : 5.157879138921816
Test model mean absolute error score : 0.825320079562973
==================================================

In [14]:
pd.DataFrame(list(zip(model_list,r2_list)),columns=["Models","R2_score"]).sort_values(by=["R2_score"])

                   Models  R2_score
6                     SVR  0.728600
2  DecisionTree Regressor  0.733396
5    KNeighbors Regressor  0.783770
7           XGB Regressor  0.821220
9                   Lasso  0.825320
3      CatBoost Regressor  0.851632
4  RandomForest Regressor  0.853581
1      AdaBoost Regressor  0.853749
0       Linear Regression  0.880433
8                   Ridge  0.880593